# Generated by Django 3.0.4 on 2020-11-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='* Campos obrigatórios', max_length=20, unique=True, verbose_name='Código da ata *')),
                ('data', models.DateField(help_text='dd/mm/aaaa', max_length=11, verbose_name='Data da reunião *')),
                ('hora', models.CharField(help_text='hh:mm', max_length=5, verbose_name='Hora da reunião *')),
                ('local', models.CharField(max_length=50, verbose_name='Local da reunião *')),
                ('pauta', models.TextField(max_length=200, verbose_name='Pauta da reunião')),
                ('texto', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Texto da reunião')),
                ('validada', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ata validada? ')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'triagem',
                'verbose_name_plural': 'triagens',
                'ordering': ['codigo', '-data', '-hora'],
                'unique_together': {('codigo', 'data', 'hora')},
            },
        ),
    ]
